name: toa_influx
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=hc6331ae_3
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.6=h9e52e59_3
  - aws-c-http=0.10.4=hffefcd8_3
  - aws-c-io=0.22.0=h20b9e97_1
  - aws-c-mqtt=0.13.3=he28f3f4_6
  - aws-c-s3=0.8.6=ha4cb493_5
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.34.3=hc2cf59f_1
  - aws-sdk-cpp=1.11.606=hffd64b9_3
  - azure-core-cpp=1.16.0=h49e36cd_1
  - azure-identity-cpp=1.12.0=h5501eda_0
  - azure-storage-blobs-cpp=12.14.0=hba864f0_1
  - azure-storage-common-cpp=12.10.0=h5501eda_3
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py310h73ae2b4_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - capnproto=1.2.0=h3a793f1_0
  - cartopy=0.25.0=py310hed136d8_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h29418f3_1
  - cfgrib=0.9.15.1=pyhd8ed1ab_0
  - cfitsio=4.6.2=h023ae6c_1
  - cftime=1.6.4=py310h8f3aa81_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh7428d3b_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py310h29418f3_1
  - dask=2025.10.0=pyhcf101f3_0
  - dask-core=2025.10.0=pyhcf101f3_0
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2025.10.0=pyhcf101f3_0
  - double-conversion=3.3.1=he0c23c2_0
  - eccodes=2.44.0=h2bffdaa_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - findlibs=0.1.2=pyhd8ed1ab_0
  - fmt=11.2.0=h1d4551f_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310hdb0e946_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gdal=3.10.3=py310h2ed3b37_22
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.0=hdade9fe_0
  - geotiff=1.7.4=h86c3423_2
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py310hb7e4da9_100
  - harfbuzz=12.1.0=h5f2951f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_he30205f_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kealib=1.6.2=h5949fbd_1
  - kiwisolver=1.4.9=py310h1e1005b_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libarrow=21.0.0=h553f2f9_5_cuda
  - libarrow-acero=21.0.0=h7d8d6a5_5_cuda
  - libarrow-compute=21.0.0=h2db994a_5_cuda
  - libarrow-dataset=21.0.0=h7d8d6a5_5_cuda
  - libarrow-substrait=21.0.0=hf865cc0_5_cuda
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.4=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.16.0=h43ecb02_0
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgdal=3.10.3=hafd5c6c_22
  - libgdal-core=3.10.3=h1dbae3e_18
  - libgdal-fits=3.10.3=hcff14e6_18
  - libgdal-grib=3.10.3=h8ff101f_18
  - libgdal-hdf4=3.10.3=ha47b6c4_18
  - libgdal-hdf5=3.10.3=h0f01001_18
  - libgdal-jp2openjpeg=3.10.3=hf58e487_18
  - libgdal-kea=3.10.3=hea5172e_18
  - libgdal-netcdf=3.10.3=hbb26ad1_18
  - libgdal-pdf=3.10.3=h2c2eb3f_18
  - libgdal-pg=3.10.3=h103a44d_18
  - libgdal-postgisraster=3.10.3=h103a44d_18
  - libgdal-tiledb=3.10.3=h88e1fbc_18
  - libgdal-xls=3.10.3=h93cc17c_18
  - libglib=2.86.0=h5f26cbf_0
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libnetcdf=4.9.3=nompi_h7d90bef_103
  - libparquet=21.0.0=h24c48c9_5_cuda
  - libpng=1.6.50=h7351971_1
  - libpq=17.6=h063c6db_2
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.08.12=h0eb2380_1
  - librttopo=1.1.0=h5ff11c1_19
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libspatialite=5.1.0=h9d118f5_16
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h550210a_0
  - libutf8proc=2.11.0=h0b34c2f_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxml2-devel=2.15.1=ha29bfb0_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py310h9bee13f_1
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib=3.10.7=py310h5588dad_0
  - matplotlib-base=3.10.7=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2024.2.2=h57928b3_16
  - msgpack-python=1.1.2=py310he9f1925_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.9.0=pyhcf101f3_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.3=nompi_py310ha66b418_100
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - orc=2.2.0=h0018cbe_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310hb3a2f59_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - poppler=25.07.0=h813ae87_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=17.6=h28188f2_2
  - proj=9.6.2=h7990399_2
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py310h29418f3_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py310h5588dad_1
  - pyarrow-core=21.0.0=py310h54c75c4_1_cuda
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.11.0=py310hf80745b_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.1=py310h61ea1ad_1
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pyside6=6.9.3=py310h96c60bd_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-eccodes=2.44.0=py310h8f3aa81_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyyaml=6.0.3=py310hdb0e946_0
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_0
  - rasterio=1.4.3=py310h9f9a88e_2
  - re2=2025.08.12=ha104f34_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rioxarray=0.19.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py310h57f9f94_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - spdlog=1.15.3=h430ee68_1
  - sqlite=3.50.4=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=h18a62a1_3
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiledb=2.28.1=h535589a_2
  - tk=8.6.13=h2c6b04d_2
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py310h29418f3_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py310h29418f3_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.25.0=py310h1637853_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - atlite==0.4.1
      - bottleneck==1.6.0
      - cdsapi==0.7.7
      - ecmwf-datastores-client==0.4.0
      - multiurl==0.3.7
      - numexpr==2.14.1
      - progressbar2==4.5.0
      - python-utils==3.9.1
prefix: C:\Users\gohng\.conda\envs\atlite_clean
